use chosen_update suggested by bottlerocket API
bottlerocket-os/bottlerocket-update-operator pull request #131
Opened 2021-12-09 03:40 UTC by gthao313

We should implement this by doing away with available_versions on
 the BottlerocketNode custom resource status, and replacing it
instead with an atrribute indicating a single version

**Issue number:**
#108

**Description of changes:**
use chosen_update suggested by bottlerocket API instead of using available_versions on the BottlerocketNode custom resource status

**Testing done:**
```
[tianhg@ip-172-31-39-243 bottlerocket-update-operator]$ kubectl -n brupop-bottlerocket-aws get brn
NAME                                               STATE   VERSION   TARGET STATE   TARGET VERSION
brn-ip-192-168-72-229.us-west-2.compute.internal   Idle    1.4.1     Idle
brn-ip-192-168-77-39.us-west-2.compute.internal    Idle    1.4.1     Idle
brn-ip-192-168-79-207.us-west-2.compute.internal   Idle    1.4.1     Idle
```

brn status
```
[tianhg@ip-172-31-39-243 bottlerocket-update-operator]$ kubectl -n brupop-bottlerocket-aws describe brn brn-ip-192-168-72-229.us-west-2.compute.internal
Name:         brn-ip-192-168-72-229.us-west-2.compute.internal
Namespace:    brupop-bottlerocket-aws
Labels:       <none>
Annotations:  <none>
API Version:  brupop.bottlerocket.aws/v1
Kind:         BottlerocketNode
Metadata:
  Creation Timestamp:  2021-12-09T03:12:20Z
  Generation:          7
  Managed Fields:
    API Version:  brupop.bottlerocket.aws/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .:
          k:{"uid":"1e1daba1-aec2-475b-9558-8daf2c55feec"}:
            .:
            f:apiVersion:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:state:
      f:status:
        .:
        f:current_state:
        f:current_version:
        f:target_version:
    Manager:    unknown
    Operation:  Update
    Time:       2021-12-09T03:12:40Z
  Owner References:
    API Version:     v1
    Kind:            Node
    Name:            ip-192-168-72-229.us-west-2.compute.internal
    UID:             1e1daba1-aec2-475b-9558-8daf2c55feec
  Resource Version:  62978978
  UID:               753ce7a4-a511-4457-8466-9e3461de560c
Spec:
  State:  Idle
Status:
  current_state:    Idle
  current_version:  1.4.1
  target_version:   1.4.1
Events:             <none>

```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2021-12-09 18:57 UTC, webern approved these changes

2021-12-09 18:57 UTC, webern commented on agent/src/apiclient.rs
> +    pub arch: String,
`pub(super)`?

2021-12-09 19:51 UTC, cbgbt requested changes

2021-12-09 19:51 UTC, cbgbt commented on models/src/node/mod.rs
> +    // TODO We haven't configured validations against `target_version`, but we are planning to remove this field.
We can replace this comment with the same `#[validate()]` line above.

2021-12-09 19:51 UTC, cbgbt commented on controller/src/statemachine.rs
>                      // If there's a newer version available, then begin updating to that version.
This comment can be removed.

2021-12-09 19:51 UTC, cbgbt commented on controller/src/statemachine.rs
> +                        .filter(|target_version| &node_status.current_version() < target_version)
In this case we just want the `current_version() != target_version`, since you could technically use brupop to initiate a downgrade.

2021-12-09 23:16 UTC, cbgbt approved these changes
:shipit:

2021-12-10 18:20 UTC, webern approved these changes

2021-12-10 21:08 UTC, merged