0.2.0-agent Integrate tracing for logging and telemetry
bottlerocket-os/bottlerocket-update-operator pull request #136
Opened 2022-01-18 02:38 UTC by gthao313

integrate tracing for logging and telemetry. Meanwhile, improving agent
logging to exit with instrumental error message.

**Issue number:**
#105

**Description of changes:**
```
commit 888a4d33181a0d8344ce80197bc293449d3e47cd (HEAD -> 0.2.0, origin/0.2.0)
Author: Tianhao Geng <tianhg@amazon.com>
Date:   Tue Jan 18 02:27:48 2022 +0000

    Add tracing support to agent

    integrate tracing for logging and telemetry. Meanwhile, improving agent
    logging to exit with instrumental error message.
```

**Testing done:**
Burpop integration test 
```
[tianhg@ip-172-31-39-243 bottlerocket-update-operator]$ kubectl -n brupop-bottlerocket-aws get pod
NAME                                           READY   STATUS    RESTARTS   AGE
brupop-agent-4rlf4                             1/1     Running   1          25m
brupop-agent-cp9d5                             1/1     Running   1          24m
brupop-agent-jpg5c                             1/1     Running   1          25m
brupop-apiserver-677496b7c4-78598              1/1     Running   1          25m
brupop-apiserver-677496b7c4-9snxq              1/1     Running   1          25m
brupop-apiserver-677496b7c4-s6tfs              1/1     Running   1          25m
brupop-controller-deployment-dbb96dcdd-xgnln   1/1     Running   1          25m
```
```
[tianhg@ip-172-31-39-243 bottlerocket-update-operator]$ kubectl -n brupop-bottlerocket-aws get brn
NAME                                                STATE   VERSION   TARGET STATE   TARGET VERSION
brn-ip-192-168-134-24.us-west-2.compute.internal    Idle    1.5.2     Idle
brn-ip-192-168-145-103.us-west-2.compute.internal   Idle    1.5.2     Idle
brn-ip-192-168-148-180.us-west-2.compute.internal   Idle    1.5.2     Idle
```

tracing log
```
{"v":0,"name":"agent","msg":"[CREATE_BOTTLEROCKET_NODE - START]","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:12:34.408104324+00:00","target":"apiserver::client::webclient","line":100,"file":"apiserver/src/client/webclient.rs","self":"K8SAPIServerClient { k8s_projected_token_path: \"/var/run/secrets/tokens/bottlerocket-agent-service-account-token\" }","req":"CreateBottlerocketNodeRequest { node_selector: BottlerocketNodeSelector { node_name: \"ip-192-168-145-103.us-west-2.compute.internal\", node_uid: \"5c0bdde7-5fe5-4a2f-86ae-599a8e8adb80\" } }"}
{"v":0,"name":"agent","msg":"[CREATE_BOTTLEROCKET_NODE - END]","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:12:44.072219732+00:00","target":"apiserver::client::webclient","line":100,"file":"apiserver/src/client/webclient.rs","self":"K8SAPIServerClient { k8s_projected_token_path: \"/var/run/secrets/tokens/bottlerocket-agent-service-account-token\" }","elapsed_milliseconds":9664,"req":"CreateBottlerocketNodeRequest { node_selector: BottlerocketNodeSelector { node_name: \"ip-192-168-145-103.us-west-2.compute.internal\", node_uid: \"5c0bdde7-5fe5-4a2f-86ae-599a8e8adb80\" } }"}
{"v":0,"name":"agent","msg":"Brn has been created.","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:12:44.072260593+00:00","target":"agent::agentclient","line":193,"file":"agent/src/agentclient.rs","brn_name":"\"ip-192-168-145-103.us-west-2.compute.internal\""}
{"v":0,"name":"agent","msg":"API server busy, retrying later ...","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:12:44.147004689+00:00","target":"agent::apiclient","line":140,"file":"agent/src/apiclient.rs"}
{"v":0,"name":"agent","msg":"API server busy, retrying later ...","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:12:54.153848868+00:00","target":"agent::apiclient","line":140,"file":"agent/src/apiclient.rs"}
{"v":0,"name":"agent","msg":"[UPDATE_BOTTLEROCKET_NODE - START]","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:13:04.157490964+00:00","target":"apiserver::client::webclient","line":140,"file":"apiserver/src/client/webclient.rs","req":"UpdateBottlerocketNodeRequest { node_selector: BottlerocketNodeSelector { node_name: \"ip-192-168-145-103.us-west-2.compute.internal\", node_uid: \"5c0bdde7-5fe5-4a2f-86ae-599a8e8adb80\" }, node_status: BottlerocketNodeStatus { current_version: \"1.1.1\", target_version: \"1.5.2\", current_state: Idle } }","self":"K8SAPIServerClient { k8s_projected_token_path: \"/var/run/secrets/tokens/bottlerocket-agent-service-account-token\" }"}
{"v":0,"name":"agent","msg":"[UPDATE_BOTTLEROCKET_NODE - END]","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:13:04.177662932+00:00","target":"apiserver::client::webclient","line":140,"file":"apiserver/src/client/webclient.rs","elapsed_milliseconds":20,"req":"UpdateBottlerocketNodeRequest { node_selector: BottlerocketNodeSelector { node_name: \"ip-192-168-145-103.us-west-2.compute.internal\", node_uid: \"5c0bdde7-5fe5-4a2f-86ae-599a8e8adb80\" }, node_status: BottlerocketNodeStatus { current_version: \"1.1.1\", target_version: \"1.5.2\", current_state: Idle } }","self":"K8SAPIServerClient { k8s_projected_token_path: \"/var/run/secrets/tokens/bottlerocket-agent-service-account-token\" }"}
{"v":0,"name":"agent","msg":"Brn status has been updated.","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:13:04.177759595+00:00","target":"agent::agentclient","line":211,"file":"agent/src/agentclient.rs","brn_status":"BottlerocketNodeStatus { current_version: \"1.1.1\", target_version: \"1.5.2\", current_state: Idle }","brn_name":"\"ip-192-168-145-103.us-west-2.compute.internal\""}
{"v":0,"name":"agent","msg":"Did not detect action demand.","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:13:04.177961789+00:00","target":"agent::agentclient","line":309,"file":"agent/src/agentclient.rs"}
{"v":0,"name":"agent","msg":"API server busy, retrying later ...","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:13:04.199830654+00:00","target":"agent::apiclient","line":140,"file":"agent/src/apiclient.rs"}
{"v":0,"name":"agent","msg":"API server busy, retrying later ...","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:13:14.215023206+00:00","target":"agent::apiclient","line":140,"file":"agent/src/apiclient.rs"}
{"v":0,"name":"agent","msg":"[UPDATE_BOTTLEROCKET_NODE - START]","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:13:24.218859585+00:00","target":"apiserver::client::webclient","line":140,"file":"apiserver/src/client/webclient.rs","req":"UpdateBottlerocketNodeRequest { node_selector: BottlerocketNodeSelector { node_name: \"ip-192-168-145-103.us-west-2.compute.internal\", node_uid: \"5c0bdde7-5fe5-4a2f-86ae-599a8e8adb80\" }, node_status: BottlerocketNodeStatus { current_version: \"1.1.1\", target_version: \"1.5.2\", current_state: Idle } }","self":"K8SAPIServerClient { k8s_projected_token_path: \"/var/run/secrets/tokens/bottlerocket-agent-service-account-token\" }"}
{"v":0,"name":"agent","msg":"[UPDATE_BOTTLEROCKET_NODE - END]","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:13:24.230784300+00:00","target":"apiserver::client::webclient","line":140,"file":"apiserver/src/client/webclient.rs","req":"UpdateBottlerocketNodeRequest { node_selector: BottlerocketNodeSelector { node_name: \"ip-192-168-145-103.us-west-2.compute.internal\", node_uid: \"5c0bdde7-5fe5-4a2f-86ae-599a8e8adb80\" }, node_status: BottlerocketNodeStatus { current_version: \"1.1.1\", target_version: \"1.5.2\", current_state: Idle } }","elapsed_milliseconds":11,"self":"K8SAPIServerClient { k8s_projected_token_path: \"/var/run/secrets/tokens/bottlerocket-agent-service-account-token\" }"}
{"v":0,"name":"agent","msg":"Brn status has been updated.","level":30,"hostname":"brupop-agent-4rlf4","pid":1,"time":"2022-01-18T02:13:24.230816678+00:00","target":"agent::agentclient","line":211,"file":"agent/src/agentclient.rs","brn_name":"\"ip-192-168-145-103.us-west-2.compute.internal\"","brn_status":"BottlerocketNodeStatus { current_version: \"1.1.1\",  [...]

2022-01-19 01:46 UTC, cbgbt requested changes

2022-01-19 01:46 UTC, cbgbt commented on agent/src/agentclient.rs
>      pub async fn create_metadata_custom_resource(&mut self) -> Result<()> {
Something that I've grown quite fond of us `tracing::instrument`. It's a macro that you can associate with methods in order to automatically generate a span every time the function is called. The macro also automatically emits an `ERROR` level message if the function returns an `Err`. Pretty handy.

I'd suggest replacing the `event!` in this method with an `#[instrument(skip(self))]` on the method call.

2022-01-19 01:46 UTC, cbgbt commented on agent/src/agentclient.rs
> +        event!(Level::INFO, brn_name = ?selector.node_name, brn_status = ?brn_update, "Brn status has been updated.");
Same here, I think you might be better off using `#[instrument]`

2022-01-19 01:46 UTC, cbgbt commented on agent/src/agentclient.rs
> +                        prepare().await.context(agentclient_error::UpdateActions {
Maybe worth adding an `#[instrument]` to `run()` so that these error cases are logged?

2022-01-19 01:46 UTC, cbgbt commented on agent/Cargo.toml
>  env_logger = "0.9"
Do we still need `env_logger`?

2022-01-19 21:52 UTC, cbgbt approved these changes
Nice work! :ship:

2022-01-20 23:20 UTC, somnusfish approved these changes

2022-01-21 01:01 UTC, merged